- name: nginx playbook
  hosts: web 
  become: yes
  tasks: 
  - name: install and run the nginx 
    ansible.builtin.package: 
      name: nginx 
      state: installed 
  - name: start the nginx
    ansible.builtin.service: 
      name: nginx 
      state: started 
  - name: enable the servie 
    ansible.builtin.service:
      name: nginx 
      enabled: yes 