- name: get the vsriables from files 
  hosts: local 
  become: yes
  vars_files:
    - course-vars.yaml 
  tasks: 
  - name: print the varibles from file 
    ansible.builtin.debug: 
      msg: "Course name is {{ COURSE }}, trainer name is {{ TRAINER }}, durarion is {{ DURATION }}"